// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // --- DATABASE_URL DIRECTLY BECAUSE WE DO NOT NEED DIRECT_URL BECAUSE IT ALL WORKS WITH PRISMA SESSION POOLER (NOT TRANSACTION POOLER) ---
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
